import {InterfaceRegistry} from '../interfaces/registry.js';
export class Runtime{
 constructor(registry=new InterfaceRegistry()){this.registry=registry;this.nodes=new Set();this.topics=new Map();this.listeners=new Map();this.parameters=new Map();this.parameterTypes=new Map();this.parameterListeners=new Set();this.services=new Map();this.jobs=new Set();this.samples=new Map();this.sampleCounter=0;this.serviceCalls=[];this.parameterChanges=[];this.onChange=()=>{};this.interfaces=new Map([['std_msgs/msg/String','string data'],['example_interfaces/srv/AddTwoInts','int64 a\nint64 b\n---\nint64 sum']]);this.systemNode='/_ros2cli_daemon';this.ensureSystemTopics();}
 ensureSystemTopics(){for(const [name,type]of [['/rosout','rcl_interfaces/msg/Log'],['/parameter_events','rcl_interfaces/msg/ParameterEvent']])this.ensureTopic(name,type).publishers.add(this.systemNode);}
 addNode(node){this.nodes.add(node);for(const topic of ['/rosout','/parameter_events'])this.topics.get(topic).publishers.add(node);}
 removeNode(node){this.nodes.delete(node);this.parameters.delete(node);this.parameterTypes.delete(node);for(const t of this.topics.values()){t.publishers.delete(node);t.subscribers.delete(node);}this.removeEmptyTopics();}
 stamp(){const now=Date.now();return {sec:Math.floor(now/1000),nanosec:(now%1000)*1000000};}
 log(node,text,level=20){const message=this.registry.complete('rcl_interfaces/msg/Log',{stamp:this.stamp(),level,name:node.replace(/^\//,''),msg:String(text)});this.publish('/rosout','rcl_interfaces/msg/Log',message,{node});}
 parameterEvent(node,name,value,kind='changed_parameters',valueType){const p=this.registry.defaultMessage('rcl_interfaces/msg/ParameterValue');p.type=valueType??this.parameterTypes.get(node)?.get(name)??(typeof value==='boolean'?1:typeof value==='string'?4:Number.isInteger(value)?2:3);p[{1:'bool_value',2:'integer_value',3:'double_value',4:'string_value'}[p.type]]=value;this.publish('/parameter_events','rcl_interfaces/msg/ParameterEvent',{stamp:this.stamp(),node,new_parameters:[],changed_parameters:[],deleted_parameters:[],[kind]:[{name,value:p}]},{node});}
 ensureTopic(name,type){if(!/^\/[A-Za-z_][A-Za-z_0-9/]*$/.test(name))throw Error('Invalid topic name '+name);const t=this.topics.get(name);if(t&&t.type!==type)throw Error('Topic type mismatch: '+t.type+' versus '+type);if(!t)this.topics.set(name,{type,publishers:new Set(),subscribers:new Set()});return this.topics.get(name);}
 removeEmptyTopics(){for(const [n,t]of this.topics)if(!t.publishers.size&&!t.subscribers.size)this.topics.delete(n);this.onChange();}
 subscribe(topic,node,fn,{type=this.topics.get(topic)?.type,id=Symbol()}={}){if(!type)throw Error('Unknown topic '+topic);this.ensureTopic(topic,type).subscribers.add(node);this.listeners.set(id,{topic,node,fn});this.onChange();return()=>{this.listeners.delete(id);if(![...this.listeners.values()].some(l=>l.topic===topic&&l.node===node))this.topics.get(topic)?.subscribers.delete(node);this.removeEmptyTopics();};}
 publish(topic,type,message,publisher){const t=this.ensureTopic(topic,type);this.registry.validate(type,message);const sample=++this.sampleCounter;this.samples.set(sample,{topic,type,publisher:publisher?.node,message,receivedBy:new Set()});if(this.samples.size>100)this.samples.delete(this.samples.keys().next().value);for(const l of [...this.listeners.values()])if(l.topic===topic)l.fn(structuredClone(message),publisher,sample);this.onChange();}
 every(period,fn){if(!Number.isFinite(period)||period<0.05||period>60)throw Error('Browser timer period must be between 0.05 and 60 seconds');const id=setInterval(fn,period*1000);this.jobs.add(id);return()=>{clearInterval(id);this.jobs.delete(id);};}
 setParameter(node,name,value){const p=this.parameters.get(node);if(!p?.has(name))throw Error('Parameter not declared: '+node+' '+name);if(typeof p.get(name)!==typeof value)throw Error('Parameter type cannot change');if(typeof value==='number'&&!Number.isFinite(value))throw Error('Parameter must be finite');const parameterType=this.parameterTypes.get(node)?.get(name);if((parameterType===2||parameterType===undefined&&Number.isInteger(p.get(name)))&&typeof value==='number'&&!Number.isSafeInteger(value))throw Error('Integer parameter requires an exact integer');if(name==='publish_rate'&&(value<0.1||value>20))throw Error('publish_rate must be between 0.1 and 20 Hz');this.parameterChanges.push({node,name,value,after:this.sampleCounter});p.set(name,value);this.parameterEvent(node,name,value);for(const f of this.parameterListeners)f(node,name,value);this.onChange();}
 async callService(name,type,request){const s=this.services.get(name);if(!s)throw Error('Service not available: '+name);if(type!==s.type)throw Error('Service type mismatch');this.registry.validate(type,request);const result=await s.handler(request);this.registry.validate(type,result,true);this.serviceCalls.push({name,type,request,result});return result;}
 reset(){for(const id of this.jobs)clearInterval(id);this.jobs.clear();this.nodes.clear();this.topics.clear();this.listeners.clear();this.parameters.clear();this.parameterTypes.clear();this.parameterListeners.clear();this.services.clear();this.samples.clear();this.serviceCalls=[];this.parameterChanges=[];this.ensureSystemTopics();this.onChange();}
}
