import {BUILTIN} from './builtin.js';
export const PRIMITIVES={bool:'bool',byte:'uint8_t',char:'uint8_t',int8:'int8_t',uint8:'uint8_t',int16:'int16_t',uint16:'uint16_t',int32:'int32_t',uint32:'uint32_t',int64:'int64_t',uint64:'uint64_t',float32:'float',float64:'double',wstring:'std::wstring',string:'std::string'};
export function splitType(type,owner){const match=/^(.*?)(?:\[(\d*)\])?$/.exec(type),base=match[1],array=match[2]!==undefined,length=match[2]?Number(match[2]):null;return {base:PRIMITIVES[base]?base:base.includes('/')?(base.split('/').length===2?base.replace('/','/msg/'):base):owner.split('/')[0]+'/msg/'+base,array,length};}
export function parseMessage(source){const fields=[];for(const line of source.split('\n')){const s=line.split('#')[0].trim();if(!s)continue;const m=/^(bool|int32|int64|float32|float64|string) ([a-z][a-z0-9_]*)$/.exec(s.replace(/\s+/g,' '));if(!m||['constructor','prototype','__proto__'].includes(m?.[2]))throw Error('Custom messages support scalar bool, int32, int64, float32, float64 and string fields');if(fields.some(f=>f.name===m[2]))throw Error('Duplicate field '+m[2]);fields.push({type:m[1],name:m[2]});}if(!fields.length)throw Error('A custom message needs fields');return {fields};}
export class InterfaceRegistry{
 constructor(extra={}){this.definitions=new Map(Object.entries({...BUILTIN,...extra}));}
 add(name,record){if(!/^[a-z][a-z0-9_]*\/msg\/[A-Z][A-Za-z0-9]*$/.test(name))throw Error('Invalid custom interface name');if(BUILTIN[name])throw Error('Cannot replace a built-in interface');this.definitions.set(name,record);}
 show(name){const expand=(owner,fields,depth=0)=>fields.flatMap(f=>{const t=splitType(f.type,owner),line='  '.repeat(depth)+f.type+' '+f.name+(f.default!==undefined?' '+JSON.stringify(f.default):'');return PRIMITIVES[t.base]?[line]:[line,...expand(t.base,this.get(t.base).fields,depth+1)];});const r=this.get(name);return [...(r.constants??[]).map(c=>`${c.type} ${c.name}=${c.value}`),...expand(name,r.fields),...(r.response?['---',...(r.responseConstants??[]).map(c=>`${c.type} ${c.name}=${c.value}`),...expand(name,r.response)]:[])].join('\n');}

 get(name){const r=this.definitions.get(name);if(!r)throw Error('Unknown or unbuilt interface '+name);return r;}
 schema(){return Object.fromEntries(this.definitions);}
 validate(name,value,response=false){const record=this.get(name);const fields=response?record.response:record.fields;if(!fields)throw Error('Not a service interface');this.validateFields(fields,value,name);return value;}
 validateFields(fields,value,owner){if(!value||typeof value!=='object'||Array.isArray(value))throw Error(owner+' requires a message object');for(const key of Object.keys(value))if(!fields.some(f=>f.name===key))throw Error('Unknown field '+key);for(const f of fields){const t=splitType(f.type,owner),v=value[f.name];if(t.array){if(!Array.isArray(v)&&!ArrayBuffer.isView(v))throw Error(f.name+' must be an array');if(t.length!==null&&v.length!==t.length)throw Error(f.name+' must have '+t.length+' elements');if(v.length>1000000)throw Error('Browser message array limit exceeded');for(const x of v)this.validateScalar(t.base,x,f.name);}else this.validateScalar(t.base,v,f.name);}}
 validateScalar(type,v,label){if(!PRIMITIVES[type])return this.validate(type,v);if(type==='string'||type==='wstring'){if(typeof v!=='string')throw Error(label+' must be string');return;}if(type==='bool'){if(typeof v!=='boolean')throw Error(label+' must be bool');return;}if(typeof v!=='number'||!Number.isFinite(v))throw Error(label+' must be finite number');if(!type.startsWith('float')){const signed=type.startsWith('int'),bits=Number(type.match(/\d+/)?.[0]??8);const low=signed?-(2**(bits-1)):0,high=signed?2**(bits-1)-1:2**bits-1;if(!Number.isSafeInteger(v)||v<low||v>high)throw Error(label+' integer outside supported exact range');}else if(type==='float32'&&Math.abs(v)>3.402823466e38)throw Error(label+' exceeds float32 range');}
 defaultMessage(name){const fields=this.get(name).fields;return Object.fromEntries(fields.map(f=>{const t=splitType(f.type,name),value=()=>f.default??(['string','wstring'].includes(t.base)?'':t.base==='bool'?false:PRIMITIVES[t.base]?0:this.defaultMessage(t.base));return [f.name,t.array?Array.from({length:t.length??0},value):value()];}));}
 complete(name,input,response=false){const fields=response?this.get(name).response:this.get(name).fields;if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Message must be a mapping');const out=response?Object.fromEntries(fields.map(f=>{const single=new InterfaceRegistry({temporary:{fields:[f]}});return [f.name,single.defaultMessage('temporary')[f.name]];})):this.defaultMessage(name);for(const [key,v]of Object.entries(input)){const f=fields.find(f=>f.name===key);if(!f)throw Error('Unknown field '+key);const t=splitType(f.type,name);out[key]=!t.array&&!PRIMITIVES[t.base]?this.complete(t.base,v):v;}this.validate(name,out,response);return out;}
 cppHeaders(){
  const headers={},done=new Set(),cpp=name=>name.replaceAll('/','::'),snake=s=>s.replace(/([A-Z]+)([A-Z][a-z])/g,'$1_$2').replace(/([a-z0-9])([A-Z])/g,'$1_$2').toLowerCase();
  const emit=name=>{if(done.has(name))return;done.add(name);const r=this.get(name),parts=name.split('/'),fields=[...r.fields,...r.response??[]];for(const f of fields){const t=splitType(f.type,name);if(!PRIMITIVES[t.base])emit(t.base);}
   const struct=(n,fs,constants=r.constants??[])=>`struct ${n}{using SharedPtr=std::shared_ptr<${n}>;using ConstSharedPtr=std::shared_ptr<const ${n}>;${fs.map(f=>{const t=splitType(f.type,name),base=PRIMITIVES[t.base]??cpp(t.base),type=t.array?(t.length!==null?`std::array<${base},${t.length}>`:`std::vector<${base}>`):base;return `${type} ${f.name}${f.default!==undefined?'{'+JSON.stringify(f.default)+'}':'{}'};`;}).join('')}${constants.map(c=>`static constexpr ${PRIMITIVES[c.type]} ${c.name}=${c.value};`).join('')}};`;
   const trait=(n,fs)=>`template<> struct MessageTraits<${n}>{static const char* type(){return "${name}";}static ${n} decode(std::string p=""){${n} m;${fs.map(f=>{const t=splitType(f.type,name),path=`p+"${f.name}"`,base=PRIMITIVES[t.base]??cpp(t.base);return t.array?`{auto q=${path};int count=kn_field_length(q.data(),q.size());${t.length===null?`m.${f.name}.resize(count);`:''}for(int i=0;i<count;i++)m.${f.name}[i]=read<${base}>(q+"."+std::to_string(i));}`:`m.${f.name}=read<${base}>(${path});`;}).join('')}return m;}static std::string encode(const ${n}& m){return std::string("{")+${fs.length?fs.map((f,i)=>`${JSON.stringify((i?',':'')+'"'+f.name+'":')}+encode_value(m.${f.name})`).join('+'):'std::string()'}+"}";}};`;
   let body=r.response?struct(parts[2],[]).replace('};',struct('Request',r.fields)+struct('Response',r.response,r.responseConstants??[])+'};'):struct(parts[2],r.fields);
   if(r.response)body=`struct ${parts[2]}{${struct('Request',r.fields)}${struct('Response',r.response,r.responseConstants??[])}};`;
   const includes=fields.map(f=>splitType(f.type,name).base).filter(t=>!PRIMITIVES[t]).map(t=>'#include <'+t.split('/').slice(0,2).join('/')+'/'+snake(t.split('/')[2])+'.hpp>').join('\n');
   headers['/include/'+parts.slice(0,2).join('/')+'/'+snake(parts[2])+'.hpp']=`#pragma once\n#include <lab_types.hpp>\n${includes}\nnamespace ${parts[0]}{namespace ${parts[1]}{${body}}}\nnamespace kinenest{${r.response?trait(cpp(name)+'::Request',r.fields)+trait(cpp(name)+'::Response',r.response):trait(cpp(name),r.fields)}}\n`;
  };for(const name of this.definitions.keys())emit(name);return headers;
 }
}
