import{parseScalar,parseMapping}from'./literals.js';
import{FileSystem}from'./fs.js';import{Terminal}from'./shell.js';import{Workspace,Builder,ROOT,BASE_PACKAGES}from'./workspace.js';import{Runtime}from'./runtime/graph.js';import{ProcessManager}from'./bridge/processes.js';
export class Lab{
 constructor({onChange=()=>{},onOutput=()=>{}}={}){this.onChange=onChange;this.onOutput=onOutput;this.fs=new FileSystem();this.workspace=new Workspace(this.fs);this.builder=new Builder(this.workspace);this.runtime=new Runtime(this.workspace.registry);this.terminals=new Map();this.nextTerminal=0;this.processes=new ProcessManager(this.runtime,this.workspace,{onChange:()=>{this.onChange();},onOutput:(p,s)=>this.output(p.terminal,s)});this.runtime.onChange=onChange;this.fs.listeners.add(onChange);}
 output(id,s){this.terminals.get(id)?.output(s);this.onOutput(id,s);}
 terminal(){const t=new Terminal(this.fs,++this.nextTerminal,{output:s=>{},dispatch:(t,w)=>this.dispatch(t,w)});this.terminals.set(t.id,t);return t;}
 stop(id){this.processes.stopTerminal(id);this.terminals.get(id)?.stop();this.onChange();}
 close(id){this.stop(id);this.terminals.delete(id);this.onChange();}
 reset(){this.builder.cancel();this.processes.reset();for(const t of this.terminals.values())t.stop();this.runtime.reset();this.terminals.clear();}
 async dispatch(t,w){const [cmd,sub,...args]=w,fs=this.fs,r=this.runtime,workspace=this.workspace;const need=(n)=>{if(args.length!==n)throw Error('Usage: '+cmd+' '+sub+' (expected '+n+' arguments)');};
  if(cmd==='python3'){const {runPythonShell}=await import('./python/shell.js');return runPythonShell(this,t,w.slice(1));}
  if(cmd==='source'){if(w.length!==2)throw Error('Usage: source <setup.bash>');const p=t.path(sub);fs.read(p);if(p==='/opt/ros/jazzy/setup.bash'){t.env.ROS_DISTRO='jazzy';return '';}const match=/^(.*)\/install\/(?:local_)?setup\.bash$/.exec(p);if(!match||!fs.exists(match[1]+'/install/COLCON_IGNORE'))throw Error('Only generated ROS setup files can be sourced');const root=match[1];t.overlays.add(root);t.env.AMENT_PREFIX_PATH=[...[...t.overlays].reverse().map(base=>base+'/install'),'/opt/ros/jazzy'].join(':');return '';}
  if(cmd==='colcon'){if(sub!=='build'||(args.length&&!(args[0]==='--packages-select'&&args.length>1)))throw Error('Supported: colcon build [--packages-select name ...]');const started=Date.now(),cwd=t.cwd;t.busy=true;t.stopTask=()=>this.builder.cancel();const summary=count=>'Summary: '+count+' package'+(count===1?'':'s')+' finished ['+((Date.now()-started)/1000).toFixed(2)+'s]';try{const built=await this.builder.build(args.length?args.slice(1):null,s=>this.output(t.id,s),cwd);const result=summary(built.length);fs.write(cwd+'/log/build.txt',result+'\n');return result;}catch(error){if(['Build cancelled','A build is already running'].includes(error.message))throw error;const result=error.message+'\n\n'+summary(this.builder.finished?.length??0)+(this.builder.failed?'\n  1 package failed: '+this.builder.failed:'');if(fs.exists(cwd+'/log'))fs.write(cwd+'/log/build.txt',result+'\n');throw Error(result);}finally{t.busy=false;t.stopTask=null;}}
  if(cmd!=='ros2')throw Error('Unknown command');
  if(sub==='-h'||sub==='--help'||!sub)return 'ROS 2 Basics Lab CLI (bounded Jazzy model)\nCommands: pkg, run, node, topic, interface, param, service, launch\nUse ros2 <command> --help for supported forms.';
  for(let i=0;i<args.length;i++)if(args[i]==='-h')args[i]='--help';
  if(!args.length&&['pkg','node','topic','param','service','run','launch','interface'].includes(sub))args.push('--help');
  if(sub==='pkg'){
   const [action,...a]=args;
   if(action==='--help')return 'ros2 pkg create --build-type ament_python|ament_cmake --license Apache-2.0 [--node-name hello] name [--dependencies rclpy std_msgs]\nros2 pkg list\nros2 pkg executables <package>';
   if(action==='list'&&a.length===0)return [...BASE_PACKAGES,...workspace.visible(t)].sort().join('\n');
   if(action==='executables'&&a.length===1){const p=workspace.resolve(t,a[0]);return [...p.executables.keys()].map(e=>a[0]+' '+e).join('\n');}
   if(action==='create'){let type='ament_cmake',license='Apache-2.0',node=null,name=null,dependencies=[];for(let i=0;i<a.length;i++){if(a[i]==='--build-type')type=a[++i];else if(a[i]==='--license')license=a[++i];else if(a[i]==='--node-name')node=a[++i];else if(a[i]==='--dependencies'){dependencies=a.slice(i+1);break;}else if(a[i].startsWith('-')||name)throw Error('Unsupported pkg create argument '+a[i]);else name=a[i];}if(!name)throw Error('Package name is required (place it before --dependencies)');const created=[];workspace.create(name,type,{cwd:t.cwd,license,node,dependencies,report:line=>created.push(line)});
    const list=values=>'['+values.map(value=>"'"+value+"'").join(', ')+']';
    return ['going to create a new package','package name: '+name,'destination directory: '+t.cwd,'package format: 3','version: 0.0.0','description: ROS 2 Basics Lab student package',"maintainer: ['Student <student@example.com>']",'licenses: '+list([license]),'build type: '+type,'dependencies: '+list(dependencies),...(node?['node_name: '+node]:[]),...created].join('\n');}
   throw Error('Use ros2 pkg --help');
  }
  if(sub==='run'||sub==='launch'){if(args[0]==='--help')return `ros2 ${sub} <package> <${sub==='run'?'executable':'file.launch.py'}>`;need(2);workspace.resolve(t,args[0]);if(sub==='launch'){const installed=workspace.resolve(t,args[0]);const {parseLaunch}=await import('./bridge/launch.js');for(const a of parseLaunch(installed.files['launch/'+args[1]]??''))workspace.resolve(t,a.package);}t.busy=true;t.foreground='process';t.stopTask=()=>this.processes.stopTerminal(t.id);try{const result=sub==='run'?await this.processes.run(args[0],args[1],{terminal:t.id}):await this.processes.launch(args[0],args[1],{terminal:t.id});if(!result)t.busy=false;return '';}catch(e){t.busy=false;t.stopTask=null;throw e;}}
  if(sub==='node'){if(args[0]==='--help')return 'ros2 node list\nros2 node info /node';if(args[0]==='list'&&args.length===1)return [...r.nodes].sort().join('\n');if(args[0]==='info'&&args.length===2){const node=args[1];if(!r.nodes.has(node)&&node!==r.systemNode)throw Error('Node not found: '+node);return node+'\nPublishers:\n'+[...r.topics].filter(([,v])=>v.publishers.has(node)).map(([n,v])=>'  '+n+': '+v.type).join('\n')+'\nSubscribers:\n'+[...r.topics].filter(([,v])=>v.subscribers.has(node)).map(([n,v])=>'  '+n+': '+v.type).join('\n');}throw Error('Use ros2 node --help');}
  if(sub==='interface'){if(args[0]==='--help')return 'ros2 interface list\nros2 interface show package/msg/Type';const visible=n=>BASE_PACKAGES.includes(n.split('/')[0])||workspace.visible(t).includes(n.split('/')[0]);if(args[0]==='list'&&args.length===1)return [...workspace.registry.definitions.keys()].filter(visible).sort().join('\n');if(args[0]==='show'&&args.length===2){if(!visible(args[1]))throw Error('Interface package not found; build and source its workspace');return workspace.registry.show(args[1]);}throw Error('Use ros2 interface --help');}
  if(sub==='topic'){
   const[action,name]=args;if(action==='--help')return 'ros2 topic list\nros2 topic type|info|echo|hz /topic\nros2 topic pub --once /topic package/msg/Type \'{"field": value}\'';
   if(action==='list'&&(args.length===1||args.length===2&&['-t','--show-types'].includes(args[1])))return [...r.topics].sort(([a],[b])=>a.localeCompare(b)).map(([name,topic])=>name+(args.length===2?' ['+topic.type+']':'')).join('\n');
   if(action==='pub'){
    let once=false,rate=1;const positional=[];for(let i=1;i<args.length;i++){if(args[i]==='--once')once=true;else if(args[i]==='-r'||args[i]==='--rate')rate=Number(args[++i]);else positional.push(args[i]);}
    if(positional.length!==3||!Number.isFinite(rate)||rate<1/60||rate>20)throw Error('Use ros2 topic pub [--once | -r 1] /topic type "{field: value}" (1/60–20 Hz)');
    const[topic,type,payload]=positional;if(!BASE_PACKAGES.includes(type.split('/')[0])&&!workspace.visible(t).includes(type.split('/')[0]))throw Error('Interface package not found');
    const message=r.registry.complete(type,parseMapping(payload));const node='/_ros2cli_pub_'+t.id;
    const process=this.processes.task('topic pub',t.id,()=>{r.ensureTopic(topic,type).publishers.add(node);r.addNode(node);const send=()=>r.publish(topic,type,message,{node});send();const dispose=once?()=>{}:r.every(1/rate,send);return()=>{dispose();r.removeNode(node);r.topics.get(topic)?.publishers.delete(node);r.removeEmptyTopics();};});
    if(once){this.processes.stop(process.id);return 'Published once';}t.busy=true;t.foreground='process';t.stopTask=()=>this.processes.stop(process.id);return 'Publishing at '+rate+' Hz. Ctrl+C stops the publisher.';
   }
   const verbose=action==='info'&&args.length===3&&args[2]==='-v';if(args.length!==2&&!verbose)throw Error('Use ros2 topic --help');const topic=r.topics.get(name);if(!topic)throw Error('Unknown topic: '+name);if(action==='type')return topic.type;if(action==='info')return `Type: ${topic.type}\nPublisher count: ${topic.publishers.size}\nSubscription count: ${topic.subscribers.size}`+(verbose?`\nPublishers:\n${[...topic.publishers].join("\n")}\nSubscribers:\n${[...topic.subscribers].join("\n")}`:'');
   if(['echo','hz'].includes(action)){const node='/_ros2cli_'+t.id;r.addNode(node);let count=0,start=performance.now();const dispose=r.subscribe(name,node,msg=>{if(action==='echo')this.output(t.id,JSON.stringify(msg,null,2).slice(0,6000)+'\n---');else{count++;const elapsed=(performance.now()-start)/1000;if(elapsed>=1){this.output(t.id,'average rate: '+(count/elapsed).toFixed(2)+' Hz');count=0;start=performance.now();}}});const process=this.processes.task('topic '+action,t.id,()=>()=>{dispose();r.removeNode(node);this.onChange();});t.busy=true;t.foreground='process';t.stopTask=()=>this.processes.stop(process.id);return '';}
   throw Error('Use ros2 topic --help');
  }
  if(sub==='param'){const[action,node,name,...value]=args;if(action==='--help')return 'ros2 param list [ /node ]\nros2 param get /node name\nros2 param set /node name value';if(action==='list'&&args.length<=2)return [...r.parameters].filter(([n])=>!node||node===n).map(([n,p])=>n+'\n'+[...p.keys()].map(k=>'  '+k).join('\n')).join('\n');if(action==='get'&&args.length===3){if(!r.parameters.get(node)?.has(name))throw Error('Parameter not found');return JSON.stringify(r.parameters.get(node).get(name));}if(action==='set'&&args.length===4){r.setParameter(node,name,parseScalar(value[0]));return 'Set parameter successful';}throw Error('Use ros2 param --help');}
  if(sub==='service'){const[action,name,type,request]=args;if(action==='--help')return 'ros2 service list\nros2 service type /service\nros2 service call /service type \'{"a": 2, "b": 3}\'';if(action==='list'&&args.length===1)return [...r.services.keys()].join('\n');if(action==='type'&&args.length===2){if(!r.services.has(name))throw Error('Service not found');return r.services.get(name).type;}if(action==='call'&&args.length===4)return JSON.stringify(await r.callService(name,type,parseMapping(request)),null,2);throw Error('Use ros2 service --help');}
  throw Error("ros2: error: invalid choice: '"+sub+"' (choose from 'pkg', 'run', 'node', 'topic', 'interface', 'param', 'service', 'launch'). Use ros2 --help.");
 }
}