import {migrateCurriculum} from './curriculum-session.js';
import {snapshotLesson,restoreLesson} from './course/checks.js';
const DATABASE='ros2-basics-lab-session';
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE,1);request.onupgradeneeded=()=>request.result.createObjectStore('sessions');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function loadSession(){const db=await database();try{return await new Promise((resolve,reject)=>{const request=db.transaction('sessions').objectStore('sessions').get('current');request.onsuccess=()=>resolve(migrateCurriculum(request.result));request.onerror=()=>reject(request.error);});}finally{db.close();}}
export async function saveSession(record){const db=await database();try{await new Promise((resolve,reject)=>{const tx=db.transaction('sessions','readwrite');tx.objectStore('sessions').put(serializableRecord(record),'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Session save aborted'));});}finally{db.close();}}
function portablePackages(packages){return new Map([...packages??[]].map(([name,record])=>[name,{...record,executables:new Map([...record.executables].map(([name,entry])=>{const copy={...entry};if(copy.wasmBytes)delete copy.module;return [name,copy];}))}]));}
export function captureSession(lab,ui){const workspace=snapshotLesson(lab);workspace.installed=portablePackages(workspace.installed);workspace.installations=portablePackages(workspace.installations);return {version:1,curriculumVersion:2,savedAt:Date.now(),workspace,terminals:[...lab.terminals.values()].map(t=>({cwd:t.cwd,env:{...t.env},vars:{...t.vars},overlays:new Set(t.overlays),history:[...t.history]})),exported:!!lab.exported,ui};}
export function restoreSession(lab,record){record=migrateCurriculum(record);if(record.version!==1)throw Error('This saved session uses an unsupported version.');restoreLesson(lab,record.workspace);lab.exported=record.exported;return record.terminals.map(t=>({...t,env:lab.workspace.restoreEnvironment(t.env),vars:{...t.vars}}));}

export async function restoreCompiledModules(record){if(record?.other)await restoreCompiledModules(record.other);for(const packages of [record?.workspace.installed,record?.workspace.installations])for(const pkg of packages?.values()??[])for(const entry of pkg.executables.values())if(entry.wasmBytes)entry.module=await WebAssembly.compile(entry.wasmBytes);return record;}

function serializableRecord(record){const workspace={...record.workspace,installed:portablePackages(record.workspace.installed),installations:portablePackages(record.workspace.installations)};return {...record,workspace,...(record.other?{other:serializableRecord(record.other)}:{})};}
